---
homebrew_prefix: /usr/local
homebrew_install_path: "{{ homebrew_prefix }}/Homebrew"
homebrew_brew_bin_path: /usr/local/bin

homebrew_installed_packages:
  - adns
  - ansible-lint
  - autoconf
  - aws-elasticbeanstalk
  - awscli
  - bash
  - bash-completion
  - boost
  - chromedriver
  - csvprintf
  - curl
  - ddrescue
  - dockutil
  - ffmpeg
  - gdbm
  - gettext
  - git
  - git-secrets
  - gmp
  - gnupg
  - gnutls
  - go
  - gradle
  - groovy
  - htop
  - htop-osx
  - hub
  - hugo
  - icu4c
  - jasper
  - jmeter
  - jpeg
  - jq
  - jx
  - kpcli
  - kubernetes-cli
  - kubernetes-helm
  - lame
  - libassuan
  - libev
  - libffi
  - libgcrypt
  - libgpg-error
  - libidn2
  - libksba
  - libpng
  - libtasn1
  - libtiff
  - libunistring
  - libusb
  - libyaml
  - mas
  - maven
  - mplayer
  - mysql
  - netcat
  - netpbm
  - nettle
  - nmap
  - npth
  - nvm
  - oniguruma
  - openssh
  - openssl
  - openssl@1.1
  - p11-kit
  - pinentry
  - pkg-config
  - putty
  - python
  - python@2
  - rbenv
  - readline
  - ruby-build
  - selenium-server-standalone
  - shellcheck
  - sqlite
  - ssh-copy-id
  - telnet
  - tree
  - watch
  - wget
  - x264
  - xvid
  - xz
  - youtube-dl
  - zsh
  - zsh-completions

homebrew_uninstalled_packages: []

homebrew_upgrade_all_packages: no

homebrew_taps:
  - homebrew/core
  - caskroom/cask

homebrew_cask_apps:
  - 1password
  - adobe-air
  - alfred
  - appcleaner
  - authy
  - beyond-compare
  - calibre
  - charlessoft-timetracker
  - cleanmymac
  - cyberduck
  - daisydisk
  - deckset
  - docker
  - dropbox
  - duet
  - etcher
  - evernote
  - fliqlo
  - gitkraken
  - google-chrome
  - gpg-suite
  - iterm2
  - keepassx
  - mactracker
  - minikube
  - namebench
  - ngrok
  - omnidisksweeper
  - pgadmin4
  - quickbooks-online
  - razorsql
  - sizeup
  - skype
  - slack
  - spotify
  - stay
  - steam
  - sublime-text
  - synergy
  - tunnelblick
  - vagrant
  - virtualbox
  - virtualbox-extension-pack
  - vlc
  - vnc-viewer
  - whatsapp
  - wireshark

# https://www.jverdeyen.be/mac/downgrade-brew-cask-application/
# https://github.com/caskroom/homebrew-cask
homebrew_cask_apps_fixed_versions:
  # This version of chefdk (1.5.0) has 2.3 version of Ruby which is needed for keepass-static gem to work
  chefdk:
    raw_url: https://raw.githubusercontent.com/caskroom/homebrew-cask/241ca06c0debf23880283430a1a7474b5e4f26ee/Casks/chefdk.rb
    creates: /opt/chefdk/embedded/bin/chef

homebrew_cask_appdir: /Applications

homebrew_use_brewfile: true
homebrew_brewfile_dir: '~'
