---
- name: "{{ item }} : Check if the app is in the dock."
  shell: "dockutil --find '{{ item }}'"
  register: app_removal_command_output

- name: Debug stdout
  debug:
    msg: "{{ app_removal_command_output.stdout }}"

- name: Debug stderr
  debug:
    msg: "{{ app_removal_command_output.stderr }}"

- name: "{{ item }} : Add the app to the dock if not found."
  shell: "dockutil --remove '{{ item }}'"
  when: app_removal_command_output.stdout | search('was found')
