---
- name: "{{ item }} : Check if the app is in the dock."
  shell: "dockutil --find '{{ item }}'"
  register: remove_command_output
  failed_when: remove_command_output.stderr != ""

- name: Debug stdout
  debug:
    msg: "{{ remove_command_output.stdout }}"
    verbosity: 4

- name: Debug stderr
  debug:
    msg: "{{ remove_command_output.stderr }}"
    verbosity: 4

- name: "{{ item }} : Add the app to the dock if not found."
  shell: "dockutil --remove '{{ item }}'"
  when: remove_command_output.stdout | search('was found')
